# Generated by Django 5.1.1 on 2024-09-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
