# Generated by Django 5.1.2 on 2024-11-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
    ]
