# Generated by Django 5.1.2 on 2024-10-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_course_owner_alter_lesson_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preview',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('approved', 'Подтвержден')], default='draft', max_length=10),
        ),
    ]
