# Generated by Django 5.1.2 on 2024-11-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_studentanswer_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Правильный ответ'),
        ),
    ]
