# Generated by Django 5.1.2 on 2024-10-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_remove_course_preview_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('unapproved', 'Unapproved')], default='unapproved', max_length=10),
        ),
    ]
