# Generated by Django 5.1.2 on 2024-11-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_alter_answer_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтвержден')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
